services:
  - type: web
    name: animebot-backend
    env: docker
    plan: starter
    region: ohio
    healthCheckPath: /health/liveness
    buildCommand: docker build -t animebot-backend .
    startCommand: docker run -p $PORT:8050 -e PORT=$PORT animebot-backend
    envVars:
      - key: ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TELEGRAM_NO_THREAD_SIGNALS
        value: "1"
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USERNAME
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: REDIS_ENDPOINT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: BACKEND_API_URL
        sync: false
      - key: CLIENT_ID
        sync: false 